### ISSUE TITLE
Undefined function 'contains'

### ISSUE THREAD

**Issue by saulmezac** [methlabUZH/automagic#11]
Hi, first of all, I want to say thank you for your great work developing this tool. 
I have a problem when I type "runAutomagic", in the command window appears this error:

Undefined function 'contains' for input arguments of type 'cell'.

Error in addAutomagicPaths (line 32)
Index = contains(parts, automagic);

Error in runAutomagic (line 5)
addAutomagicPaths();

How can I solve this? I have Matlab 2016 and I followed the steps correctly (I unzipped the folder and I changed my working directory to the root folder).

**Comment by JohnSmallridge** [comment]
Hi, 
Thank you for your question
Are you running 2016a? I think the 'contain' function was introduced in MATALB 2016b
Could you try updating Matlab and see if it fixes it?
