### ISSUE TITLE
running preprocess in parallel

### ISSUE THREAD

**Issue by yvonnio** [methlabUZH/automagic#17]
Is it currently possible to run preprocess independently (e.g., submit each subject on a HPC queue) and then, upon completion, run the GUI for quality assessment?  Let's say for example after running:
```
addAutomagicPaths();

load('path/to/project/project_state.mat'); # load parameters
Params=self.params;

data=pop_fileio('path/to/data/subj1.raw'); # load data, in my case EGI-257
[EEG, varargout] = preprocess(data, Params) # run the preprocessing based on my defined params

save('path/to/results/p_subj1.mat', EEG) # save cleaned file
for f=1:size(varargout,1)
  saveas(varargout{f},['path/to/results/fig' num2str(f) '.png']) # print the output figs
end
```
Could I then pull up the saved figures using the GUI?
Thanks!

**Comment by JohnSmallridge** [comment]
It should be possible using the approach you've suggested, however, you won't be able to run preprocessing in parallel if you use PREP option (which uses parallel processing by default). 
If the figures are stored in the appropriate results folder and using the same file-name convention e.g. '_orig' then it should work. 
Thanks!
