### ISSUE TITLE
It doesn't recognise raw files

### ISSUE THREAD

**Issue by RenzoLanfranco** [methlabUZH/automagic#22]
Hi. I tried everything. It doesn't recognise raw files.

**Comment by JohnSmallridge** [comment]
Hi,
We have used .RAW files in the past without issues. Could you give some details about the MATLAB error messages which appear when you try to use .RAW files as input?

**Comment by ChenSD** [comment]
I found this toolbox did not recognize .eeg files. I tried both GUI and scripts. The MATLAB showed there were no files in the data directory.

**Comment by ChenSD** [comment]
The same thing happened to me. I fixed it by arranging data as required by the toolbox
