### ISSUE TITLE
No subjects to interpolate. Please first rate

### ISSUE THREAD

**Issue by ChenSD** [methlabUZH/automagic#29]
The scripts I used are as follows, which generated the error:"No subjects to interpolate. Please first rate".
addAutomagicPaths();
name = 'test_project';
dataFolder = 'F:\EEGData\test_emotion\test1\raw';
resultsFolder = 'F:\EEGData\test_emotion\test3_test_results\';
ext = '.set';
% parameters to preprocessing
Params = struct('FilterParams',         struct('notch', struct('freq',  50), ...
                                               'high',  struct('freq',  0.1, 'order', []),... % Default order for filtering
                                               'low',   struct('freq',  30, 'order', [])),...
                 'CRDParams',           struct('ChannelCriterion',      0.85,...
                                               'LineNoiseCriterion',    4,...
                                               'BurstCriterion',        5,...
                                               'WindowCriterion',       0.25, ...
                                               'Highpass',              [0.25 0.75]), ...
                 'MARAParams',          struct('chanlocMap', containers.Map, ...
                                               'largeMap', 0, ...
                                               'high',  struct('freq', 1.0, 'order', [])) ...
                 );
VisualisationParams = struct();
samplingrate = [];
project = Project(name, dataFolder, resultsFolder, ext, Params, VisualisationParams, samplingrate);
project.preprocessAll();
project.interpolateSelected();

**Comment by Div12345** [comment]
Hi,
As I understand it, it is likely that you have no channels that failed the criterion for bad channel detection (through Clean_rawdata in your case) or you've already done the interpolation on it before. Check the automagic structure in the mat file in the results folder and see the variable isInterpolated, tobeInterpolated and finalBadChans. I think they will be self-explanatory and you'll be able to understand which case your condition falls under.

Hope this is useful
Best
Divyesh Narayanan
