### ISSUE TITLE
EOG channels not saved at the end

### ISSUE THREAD

**Issue by Div12345** [methlabUZH/automagic#30]
Hi, 
I observed that whenever EOG channels are provided in the begining, they are removed from the variable EEG and kept separate as variable EOG and are also used fine till the end and are even plotted in the final figure. But I can't find it after that. Doesn't it get saved? If so, what should I do to get it saved.

Thanks in Advance
Divyesh Narayanan

**Comment by ksgfan** [comment]
Hi Divyesh

The indices of EOG channels are saved in 'automagic.channelReduction.usedEOGChannels'. You can get the 'automagic' struct by loading the preprocessed data as follow:

` x = load('oip_EEG.mat')

x = 

  struct with fields:

          EEG: [1×1 struct]
    automagic: [1×1 struct]`

Best,
Dawid
