### ISSUE TITLE
bids export file names strange

### ISSUE THREAD

**Issue by behinger** [methlabUZH/automagic#31]
Hi!
I want to export a BIDS dataset using:
```project.exportToBIDS('local',0,0,0,1)```

I get:
```
newResFile =     'localderivatives\automagic-pipeline\sub-001\eeg\sub-sub-001_np_sub-001_eeg_sub-001_task-P3_eeg_eeg.set'
```
in processing, which is clearly not what I wanted :S

two immediate problems a) the function should use fullfile to add a "\" or "/" between my "folder" and the additional derivates
b) the function should extract already specified BIDS format of the original dataset, or at least give me some option to specify the filenames

Hope that helps!
Best, Bene

**Comment by ksgfan** [comment]
Hi Bene
Thank you for the input, it's fixed and committed to the dev branch.

Best,
Dawid
