### ISSUE TITLE
ICA Weights look strange

### ISSUE THREAD

**Issue by behinger** [methlabUZH/automagic#32]
This is what the ICA winv looks like if I plot the EEGset I receive after automagic:
![grafik](https://user-images.githubusercontent.com/10183650/98805744-55122680-2418-11eb-96b6-772ec6a17ecd.png)

These are the one I get, when I overwrite the EEG.icaact (winv etc.) with the EEG.etc.beforeICremove.icaact etc.:
![grafik](https://user-images.githubusercontent.com/10183650/98805797-7115c800-2418-11eb-9eb1-012eb3e7ff90.png)

Note that in the latter component 1 & 5 were marked for deletion. But besides that, something went wrong somewhere. The first set of components does not look at all like a usable ICA-decomposition.

I am using the normal automagic cloned from github yesterday

**Comment by ksgfan** [comment]
Hi
The problem arose when recomputing 'icawinv' using eeg_checkset after removing bad ICs. 
`icawinv = pinv(EEG.icaweights * EEG.icasphere)`
and
`icawinv = pinv(EEG.icaweights(good_comps,:) * EEG.icasphere)`
are not the same.

We fixed it - now we use 'icawinv' computed directly in pop_subcom -  and updated the master branch. 
Best,
Dawid

**Comment by behinger** [comment]
ok cool :-)
