### ISSUE TITLE
Not a valid prefix

### ISSUE THREAD

**Issue by ugpavlov** [methlabUZH/automagic#34]
![2](https://user-images.githubusercontent.com/44529854/100622740-7da78500-3321-11eb-943a-b79cc43ef259.png)
![1](https://user-images.githubusercontent.com/44529854/100622744-7e401b80-3321-11eb-9c1f-87914e15505b.png)
I tried many different paths and folder structures including BIDS and exactly the structure you show in Automagic directory hierarchy, tried to create a project using GUI and command line but the 'Not a valid prefix' error is still there.

**Comment by ksgfan** [comment]
Hi
I cannot replicate this error. Which Automagic version are you currently using? Are all the files in dataFolder called sub-001_*?
Best, Dawid

**Comment by ugpavlov** [comment]
Hi! I don't know which version it is but I downloaded it yesterday from github. As you can see on the screenshot all files are called sub-001_*.

**Comment by ksgfan** [comment]
Do you already have any preprocessed files in the result folder? If yes, how are they called?

**Comment by ugpavlov** [comment]
the result folder is empty.

**Comment by ksgfan** [comment]
Ok, could you please go to src->block.m, set a breakpoint in the line 1433, run your code again and examine, what value does the prefix get?

**Comment by ugpavlov** [comment]
It's empty.
![image](https://user-images.githubusercontent.com/44529854/100714262-cf015400-33b5-11eb-9fba-a86abde8cd9d.png)
I've solved the problem by reseting the paths to default. Far from ideal but it worked. Perhaps it was a conflict with EEGLAB but I have to investigate further. Thanks for you help.
