### ISSUE TITLE
Create Project Issue

### ISSUE THREAD

**Issue by yxlFromYSU** [methlabUZH/automagic#35]
Hello,
When I create project, it has the tip as follow:
A list of channel indices seperated by space or comma must be given to determine EOG channels
<img width="439" alt="屏幕快照 2020-12-21 下午7 28 37" src="https://user-images.githubusercontent.com/38976364/102772615-c9020000-43c2-11eb-800f-62c436a4c691.png">

**Comment by ksgfan** [comment]
Hi
apparently you clicked on the 'Exclude Channels' in the main GUI but provided no channels to exclude. 

<img width="543" alt="Bildschirmfoto 2020-12-21 um 13 19 34" src="https://user-images.githubusercontent.com/34235506/102776617-54fa3480-438f-11eb-91e5-571ebd514939.png">

Uncheck the 'Exclude Channels' button or provide list of channels to exclude.

Best,
Dawid

**Comment by yxlFromYSU** [comment]
Hello
This is the picture about the configure. I did not clicked on the 'Exclude Channels' in the main GUI.


Best
yxl
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "methlabUZH/automagic"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 晚上8:22
收件人:&nbsp;"methlabUZH/automagic"<automagic@noreply.github.com&gt;;
抄送:&nbsp;"1273012194"<1273012194@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [methlabUZH/automagic] Create Project Issue (#35)





 
Hi
 apparently you clicked on the 'Exclude Channels' in the main GUI but provided no channels to exclude.
 

 
Uncheck the 'Exclude Channels' button or provide list of channels to exclude.
 
Best,
 Dawid

**Comment by ksgfan** [comment]
I edited my comment a few minutes ago, please look it up again. Does it solve the problem?

**Comment by yxlFromYSU** [comment]
yes,this problem has been solved.
