### ISSUE TITLE
Unable to open graphical interface

### ISSUE THREAD

**Issue by zll00** [methlabUZH/automagic#4]
The first time I typed "runAutomagic" on the command line, it worked fine. 
![fine](https://user-images.githubusercontent.com/51576334/61575585-e06af880-aaff-11e9-8e77-06463d9666f8.png)
But when I type "runAutomagic" after exiting, it will report an error.
Then I re-downloaded this toolkit and tried again, it still reporting an error.
![error](https://user-images.githubusercontent.com/51576334/61575708-c03c3900-ab01-11e9-9c92-d09c3b23112b.png)
I am looking forward to your reply.
Thank you

**Comment by JohnSmallridge** [comment]
Hello,

You should find a folder (likely in your user directory) on your machine called 'automagicConfigs'. If you delete this and try re-installing Automagic on your Matlab path then this problem should be resolved. This is a temporary solution to this particular bug, and we will work to make sure this doesn't happen in future versions of Automagic. 

Thank you for your interest in Automagic!
