### ISSUE TITLE
multiple errors in systemDependentParse and pre-processing pipeline

### ISSUE THREAD

**Issue by kkauraiims** [methlabUZH/automagic#51]
Hello, I am trying to run the Automagic pipeline on an EGI 128 channel recording using the EGI presets of Langer lab and mostly default configurations. 
I am getting multiple errors on running the same (screenshot attached), any help in this regard would be useful. Thanks!

<img width="1166" alt="Screenshot 2021-08-31 at 1 52 35 PM" src="https://user-images.githubusercontent.com/89849204/131505785-d78fdd17-415a-44a4-8fca-a9f73135c787.png">

**Comment by ksgfan** [comment]
Hi, it seems that the `EEG.nbchan` is not 128. Could you check what value does this variable take in the EEG struct?
![Bildschirmfoto 2021-08-31 um 15 49 18](https://user-images.githubusercontent.com/34235506/131514450-8112eafa-88f6-4437-8161-8733faaa3709.png)

**Comment by kkauraiims** [comment]
Hello, for some reason, it is showing all fields, including nbchan as null! (screenshot attached). 

Just to clarify, I did not first import the data file into EEGLAB as I usually do. I simply indicated the path of the 'Study' folder as instructed in the Automagic wiki https://github.com/methlabUZH/automagic/wiki/How-to-start#how-to-create-a-new-project

<img width="1101" alt="Screenshot 2021-08-31 at 2 53 16 PM" src="https://user-images.githubusercontent.com/89849204/131515025-6b56e881-70d8-4afd-bd2f-d736989a4dbb.png">

**Comment by ksgfan** [comment]
The data was not loaded properly. 'presets of Langer lab' assume that the data is stored as a .mat file. What extension does your data have?

**Comment by kkauraiims** [comment]
Oops! So that may be the issue. It is a .mff file
While avoid using the presets and run again. Thanks! :)

The same can be mentioned in the user manual (if not there already, maybe I missed it!)

**Comment by ksgfan** [comment]
Hmm, I've never tried to load .mff files in automagic. I am not sure if it is going to work. Consider to write a short script and convert the .mff to .mat before preprocessing.
