### ISSUE TITLE
number of channels reduced even after interpolation

### ISSUE THREAD

**Issue by kkauraiims** [methlabUZH/automagic#52]
Hello, I have run Automagic on 128 channel data (EGI), however, even after using the  'interpolate all' option my output channels are still very low (118/128). I need all the channels for further downstream analysis, can someone help with this?

I have attached a sample log file for reference. 

[Praful_log.txt](https://github.com/methlabUZH/automagic/files/7195703/Praful_log.txt)

**Comment by ksgfan** [comment]
Hi,

I see from the txt file that you used EOG regression. Did you regressed out 10 EOG channels? If yes, that is the reason why they are missing. If you need those channels for further analysis, maybe try to skip  EOG regression and let the ICA correct for eye movements. 

Best,
Dawid
