### ISSUE TITLE
import Automagic results into EEGLab

### ISSUE THREAD

**Issue by silviaclementlam** [methlabUZH/automagic#53]
Hi, it's not an issue but would like to see if I could get an answer from here. I used Automagic as an eeglab extension and ran it in the EEGLAB gui. Later I tried to view the preprocessed setfile in eeglab by importing Automagic results in the EEGLAB gui. Any advice on the command line for importing automagic results in eeglab? I tried to retrieve it using eeg.history but it didn't show the code.  Thanks!

**Comment by ksgfan** [comment]
Hi, 
do you mean something like that?

```
eeglab % start eeglab
load('/Users/ds/Dropbox/automagic/test_results/AA2/ip_AA2_SL1_EEG.mat') % load preprocessed data
eegplot(EEG.data) % plot data
```

Best,
Dawid
