### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by XlZha** [methlabUZH/automagic#68]
Hi,

When I tried to creat a new project, I got the below error:

![image](https://github.com/methlabUZH/automagic/assets/118810085/f45cd339-0841-4148-80e9-b604e3ffe188)
 
And the parameters are set as below:
![image](https://github.com/methlabUZH/automagic/assets/118810085/eda1bc95-e3e7-4f2d-bcc8-d4c4d0c16e07)

Could you please tell me how to correct it?

**Comment by ksgfan** [comment]
Hi,

what is the name of the file?
could you set a breakpoint on line 1450, before creating the project? Next, create a project and check, what value the `reducedAddress` has?

If you want, I could also assist you via zoom. 

Best,
Dawid

**Comment by ksgfan** [comment]
Hi Long,

I think something went wrong, I don't see your screen shots, but only text. 

Best,
Dawid

**Comment by XlZha** [comment]
Dear Dawid,


I sent these screen shots as attached.


Best,
Long 
















At 2023-06-27 19:21:29, "ksgfan" ***@***.***> wrote:

Hi Long,

I think something went wrong, I don't see your screen shots, but only text.

Best,
Dawid
