### ISSUE TITLE
how to add raw data 

### ISSUE THREAD

**Issue by MRBMELMH** [methlabUZH/automagic#7]
Dear Nicolas,
        Firstly, thank you and your team created such a great work! It‘s awesome!
        I have a problem about how to add my EEG data to the menu?My data was recorded from the g.recorder, which can't be read in Automagic .And then I changed the file extension .set , it sill can't be read. Could you tell me the solution of this  problem?
[
![图片](https://user-images.githubusercontent.com/50815620/62410355-19828d00-b617-11e9-8713-f035a92e6bd9.png)
](url)
[
![图片](https://user-images.githubusercontent.com/50815620/62410356-22735e80-b617-11e9-8f4c-2f0c7d4028ae.png)
](url)

       Thanks  sincerely
       M.LMH

**Comment by nickilanger** [comment]
Dear Ma Rui, 

Can you import the .hdf5 files into EEGLab (without using Automagic)? If so, you can simply import the files into EEGLab first and then save it as a .mat file. It seems that you saved the files as .set. The .set format is not compatible with Automagic. 

If you have imported the files with EEGLab, MATLAB creates an structures named "EEG". Save this "EEG" structure with the "save" function:

save('yourfilename.mat','EEG')

Then Automagic can definitely load the .mat file. 

Best, 

Nicolas

**Comment by MRBMELMH** [comment]
Dear Nicolas,

Thank you for your reply ! I tried your suggestion,but it seems can't work.First, the 2019 version of EEGLAB can't save the .hdf5 files as .mat files , and i don't understand that you said "mported the files with EEGLab, MATLAB creates an structures named "EEG". Save this "EEG" structure with the "save" function“  how to realize, could you put a video or screeshoot about the solution?

Thanks  sincerely,

Ma Rui

**Comment by MRBMELMH** [comment]
Dear  Nicolas,
     
Thanks for your reply. This problem has already be solved. 
I have another question : Can I use a 64-channel data in Automagic？
 
Thanks 
Ma Rui

**Comment by nickilanger** [comment]
Dear Ma Rui, 

Nice to hear that the data import did work now. Sure, you can use 64-channel data or any other electrodes EEG system. All you need is the electrodes coordinates file for your EEG system.

**Comment by MRBMELMH** [comment]
Dear Nicolas,

Thank you for your reply.
I still want to ask one more question: how can I save the result as .set file?

Thanks sincerely,
Ma Rui

**Comment by nickilanger** [comment]
The gp_m2 is the final (cleaned) data set. If you load this one to MATLAB you will see a EEG and automagic structure. The EEG structure is the same as from EEGLab, so you can simple continue to work with EEGLab function (e.g. save as a .set file). 

Best, 

Nicolas

**Comment by MRBMELMH** [comment]
But when I save it as .set file,and load it in EEGLAB,there only have 63 channels, I don't know which channel has been excluded.  In the Automagic processing, I didn't choose to exclude any channel.If I don't know which channel has been excluded, I can't do channel location .
[
![77a8a0c47811b0b8a1868a624d261ad](https://user-images.githubusercontent.com/50815620/62527187-40d29780-b86d-11e9-8958-c171704f0e0b.png)
](url)

**Comment by nickilanger** [comment]
I don't know what settings you have used for automagic (which reference? did you use bad channel identification?). are you sure that there were 64 channels before Automagic. It might be that the reference channel is not loaded in a first place. You can check the channels by looking at the EEG.chanlocs structure.There you see the labels and coordinates of all used electrodes.

**Comment by MRBMELMH** [comment]
This is my settings:
[
![690feffc72949c7cf4fc540bad29873](https://user-images.githubusercontent.com/50815620/62528343-44671e00-b86f-11e9-95ee-50b89855d2b4.png)
](url)
[
![e6c654648b458170be8193364270451](https://user-images.githubusercontent.com/50815620/62528355-4a5cff00-b86f-11e9-99b3-7cdc0bb64d57.png)
](url)
Actually, there are 64 EEG channels and 2 EOG channels.

**Comment by nickilanger** [comment]
Did you open the raw files (before preprocessed in Automagic) in EEGlab? What's the number of channels there? or check EEG.chanlocs. 

I see in your setting that you selected two electrodes as references channel (63 and 64). Are you sure you recorded this with two reference electrodes? Are you sure they are in the raw recordings?

**Comment by MRBMELMH** [comment]
YES , I chose two reference channels ,which were putting at two earlobes. 
And now ,i have another problem that the processing  is at a standstill in PREP :
[
![图片](https://user-images.githubusercontent.com/50815620/62706164-8a63e380-ba21-11e9-813b-3c553a1f15e8.png)
](url)
And there are my settings:
[
![98a3062a5a1c549df331f37fa88ba81](https://user-images.githubusercontent.com/50815620/62706277-c434ea00-ba21-11e9-9246-4369d4abde26.png)
[
![162dc6fadf3b0317629805fe2a89d17](https://user-images.githubusercontent.com/50815620/62706299-cc8d2500-ba21-11e9-98ac-4efce794aeb7.png)
](url)
](url)

**Comment by nickilanger** [comment]
could you send me a raw file please. so i can take a look at the two reference electrode problem. 

It seems that PREP is working. It just takes a lot of processing time depending on your computer. 

Best, 

Nicolas

**Comment by MRBMELMH** [comment]
OK，I'll send my raw files to you in e-mail.

Thaanks
MA RUI

**Comment by nickilanger** [comment]
Hi Ma rui, 

I did no receive any raw files. 

Best,

Nicolas

Nicolas Langer
Assistant Professor of Methods of Plasticity Research
University of Zurich
Andreasstrasse 15 (Office AND.4.58)
8050, Zurich, Switzerland
n.langer@psychologie.uzh.ch
phone: (+41) 44 635 34 14
http://www.psychology.uzh.ch/en/areas/nec/plafor.html
