### ISSUE TITLE
Missing Warning for Required Signal Processing Toolbox Installation

### ISSUE THREAD

**Issue by MartynaPlomecka** [methlabUZH/automagic#70]
Automagic requires the Signal Processing Toolbox to be installed beforehand, but there's no warning or notification about this prerequisite. This can lead to confusion or errors for users who haven't installed the Signal Processing Toolbox yet. It would be beneficial to include a warning or note in the documentation or installation instructions. Thanks!

**Comment by ksgfan** [comment]
thanks!
